server:
  port: 8080

spring:

    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/depot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    freemarker:
      #设置是否允许HttpServletRequest属性重写（隐藏）控制器生成同名的模型属性。
      allow-request-override: false
      #设置是否允许HttpSession属性重写（隐藏）控制器生成同名的模型属性。
      allow-session-override: false
      #启用模板缓存
      cache: false
      # 模板编码
      charset: utf-8
      # 检查模板位置是否存在
      check-template-location: true
      # 内容类型值
      content-type: text/html
      # 启用mvc视图解决方案
      enabled: true
      # 是否将所有请求属性添加到与模板合并之前的模型中
      expose-request-attributes: false
      # 设置是否所有HttpSession属性应该与模板融合之前添加到模型
      expose-session-attributes: false
      # 设置是否公开一个由Spring的macro库使用RequestContext，在名为“springMacroRequestContext”。
      expose-spring-macro-helpers: true
      # 是否开启模板文件的热部署
      prefer-file-system-access: true
      # 视图前缀
      #prefix:
      # 视图后缀 默认是.ftl
      suffix: .html
      # 模板路径配置，多个模板路径用分号分割 默认是 就是classpath:/templates/
      template-loader-path: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zweb.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql